### ISSUE TITLE
Renaming the Durandal Folder Breaks the Application - make dist

### ISSUE THREAD

**Issue by akaustav** [BlueSpire/Durandal-Mimosa-Skeleton#16]
I apologize for the newbie question. But I have been unable to figure out RequireJS, Durandal and Mimosa.

I am using a Windows 7 machine and have all the prerequisite software installed. Here are the steps which I followed:
1. On command line, I download the mimosa durandal skeleton into a folder named `mimosa-test`:
   `C:\> mkdir mimosa-test`
   `C:\> cd mimosa-test`
   `C:\mimosa-test> mimosa skel:new durandal .`
2. After the previous command completed all operations, I navigated into the `assets\javascripts\vendor\` folder and renamed the `durandal` folder to `durandal-2.1.0`:
   `C:\mimosa-test> cd assets\javascripts\vendor`
   `C:\mimosa-test\assets\javascripts\vendor> mv durandal durandal-2.1.0`
3. I modified the file at assets\javascripts\app\main.js to refer to this renamed folder:
   Before:
   `requirejs.config({`
   `paths: {`
   `...`
   `'durandal':'../vendor/durandal',`
   `'plugins' : '../vendor/durandal/plugins',`
   `'transitions' : '../vendor/durandal/transitions'`
   `},`
   `...`
   `});`
   After:
   `requirejs.config({`
   `paths: {`
   `...`
   `'durandal':'../vendor/durandal-2.1.0',`
   `'plugins' : '../vendor/durandal-2.1.0/plugins',`
   `'transitions' : '../vendor/durandal-2.1.0/transitions'`
   `},`
   `...`
   `});`
4. Then I ran `make dist`.
   `C:\mimosa-test\assets\javascripts\app> cd C:\mimosa-test`
   `C:\mimosa-test> make dist`
5. I wait for the above to complete and generate the `dist` folder at `C:\mimosa-test\dist`.
6. I copy the contents of the dist folder to my Apache `htdocs` folder. When I load the application on my browser by navigating to `http://localhost/`, I get the Durandal Starter Kit splash screen and the app freezes there.
7. Upon checking the console in Firefox, it mentions:
   `Error: undefined missing plugins/dialog`

Please help me figure out how to rename the `durandal` folder and not break the application.

Ameet

**Comment by davismj** [comment]
Thanks for the report. I will investigate. However, is there a compelling reason to rename the folder?

**Comment by akaustav** [comment]
Thanks davismj for looking into this report.
We are trying to keep copies of all libraries on in the project in a folder name in the following convention: `assets\javascripts\vendor\<library>-<version>`. For example:
```
1. assets\javascripts\vendor\almond-0.2.6
2. assets\javascripts\vendor\bootstrap-3.3.1
3. assets\javascripts\vendor\durandal-2.1.0
4. assets\javascripts\vendor\jquery-2.1.1
5. assets\javascripts\vendor\knockout-3.3.0
...
```

**Comment by EisenbergEffect** [comment]
Closing for archive of this project since Mimosa itself hasn't had a single commit in almost 3yrs.
